### ISSUE TITLE
add statistics to log file

### ISSUE THREAD

**Issue by MarieLataretu** [hoelzer/clean#10]
add some small stats to the log file e.g.:

- how many reads are in clean
- how many reads are in contamination
- percentage of contamination

**Comment by hoelzer** [comment]
Related to this, it would be great to get some detailed information for cleaning against a multi-species index. For example 

23 % contamination
13 % human
5 % eco
5 % DCS

maybe this can be relatively easy done by counting the reads mapped to each single genome with samtools? something like

```bash
samtools view BAM -c contig_name
```

Or maybe there is already some statistics output from minimap2/bbduk possible?

**Comment by MarieLataretu** [comment]
Yes, I'm working on that.
`bbduk` has a nice build-in statistic; for minimap2 I didn't find something.

---

I have something like the `HISAT2` summary in mind:
```
200000 reads in total; of these:
	1972 (0.98600%) reads were properly mapped; of these:
		1205 (0.60250%) aligned to Chromosome dna:chromosome chromosome:ASM80076v1:Chromosome:1:4558660:1 REF
		767 (0.38350%) aligned to gi|9626372|ref|NC_001422.1| Enterobacteria phage phiX174 sensu lato, complete genome
```

---

For minimap2 I am playing around with `samtools idxstats`. It gives you some numbers per contig. I'm not sure what I'm missing: the total number of reads somehow differs from the number of reads in the fastq file (this holds also for `samtools flagstat` where I don't sum up by hand).
 `samtools idxstats` might count some reads multiple times if they are mapped more than once or in multiple fragments, but this does not explain fewer reads than in the fastq file.

**Comment by hoelzer** [comment]
Okay great, thanks for looking into this. An HISAT2-styled output would be great. 

@samtools yeah, it's always tricky. All the time when I tried to do something with samtools+flagstats, at the end I was always not sure if things were counted correctly. Multiple mapped reads can be one issue. Or maybe unmapped reads are not counted and that's why you get a lower count than in the original FASTQ?

**Comment by MarieLataretu** [comment]
Uu, now I see that it is always more reads than the input!

secondary and supplementary from `flagstat` are counted as mapped in `idxstats`.

How should we handle this? Just go with "more reads than in the input"?

**Comment by hoelzer** [comment]
hm... can't you set some flag to only get unique reads counted? Our goal should be to have an exact percentage of decontaminated reads in the output. 

another idea: can we tell minimap2 to only map a read once? I mean, we don't care if there are multiple mappings. When a read hits the human genome it is contamination. Then the counting with samtools might be easier?

**Comment by MarieLataretu** [comment]
Okay, I have something:

- with `-N 0` we have no secondary alignments from minimap2

But we have still supplementary reads (Bit 0x800 indicates that the corresponding alignment line is part of a chimeric alignment.  A line flagged with 0x800 is called as a supplementary line), so:

- run `samtools idxstats` on all mapped and not supplementary reads, and count the reads from the input fastq files

 All properly mapped and not supplementary reads:

- for fasta `samtools view -b -F 2052 ${name}.sam`
- for nano `samtools view -b -F 2052 ${name}.sam`
- for illumina ` samtools view -b -f 2 -F 2048 ${name}.sam`

(quite confusing and a bit ghetto, but it should work)

Are you OK with this implementation?

**Comment by hoelzer** [comment]
Sounds like a good solution to me! 

So we will simply skip alignments that are flagged as supplementary? 

How does such a supplementary (chimeric) alignment look like? One part of the read is mapping on pos X and the other on pos Y? And then per default two alignments (reads) are counted that we can avoid by setting 0x800? fine for me, then we can also state that supplementary alignments are not part of the reported statistic?

**Comment by MarieLataretu** [comment]
From the SAM Format Specification:
> Chimeric alignment: An alignment of a read that cannot be represented as a linear alignment.  A chimeric alignment is represented as a set of linear alignments that do not have large overlaps.  Typically, one of the linear alignments in a chimeric alignment is considered the “representative” alignment, and the others are called “supplementary” and are distinguished by the supplementary alignment flag.  All the  SAM records in a chimeric alignment have the same QNAME and the same values for 0x40 and 0x80flags (see Section 1.4).  The decision regarding which linear alignment is representative is arbitrary.

So, disjunctive parts of a read align to different position and different orientations; one of these alignments is the representative one, the other `x` alignments are called supplementary. All of them are flagged as mapped and we end up with `#normal aligned + x supplementary`. To get rid of the supplementary alignments, we discard everything with 0x800 set.

Anyway, we count a read as one contamination read, whether it aligned once, or multiple times as chimeric. I'd say that serves the purpose.

**Comment by hoelzer** [comment]
Thanks for the explanation! I agree, that works for us!
