### ISSUE TITLE
--list not working

### ISSUE THREAD

**Issue by MarieLataretu** [hoelzer/clean#13]
splitCsv works on strings, but not on paths

**Comment by MarieLataretu** [comment]
I, see it works, but differently than I expected

**Comment by hoelzer** [comment]
yeah, the main idea is that you can pass CSV files that look like this:

```csv
foo,ont.fastq
bar,ont2.fastq
foobar,ont3.fastq
```

and this is simply activated by adding the tag `--list`. When using `--list`, `--nano` expects a CSV instead of fastq files.

**Comment by MarieLataretu** [comment]
Yes, I clarified the help!

If `--list` is set, `--nano`, `--illumina` and `--fasta` must be csv files

**Comment by hoelzer** [comment]
Great!

MarieLataretu <notifications@github.com> schrieb am Fr., 24. Apr. 2020,
23:27:
