### ISSUE TITLE
MultiQC support

### ISSUE THREAD

**Issue by hoelzer** [hoelzer/clean#22]
* fastQC (has multiQC support)
* nanoPlot
    * currently no multiQC support, just provide a PNG figure 
    * https://github.com/hoelzer/mgnify-lr/blob/master/modules/nanoplot.nf
* bbmap (has multiQC support)
* minimap2 (currently no multiQC support, maybe just provide summary file)
* write own multiQC support for the final log.stats file (show some bar plots)

**Comment by MarieLataretu** [comment]
What is better: one MultiQC report for all the input or one MultiQC report for each input separately?

Potentially we canhave multiple fasta, multiple nanopore fastq and multiple illimina (single-end) fastq files as input for one run.

**Comment by hoelzer** [comment]
Good point. 

Does this really work? multiple {fasta, ont, ill} in one run? Or do channels clash in such a scenario? 

If it works, it's great but yes: how to do the reporting then. Intuitively, I would say that one run of the workflow will contain input data that is somehow related and thus a single report should be fine (if possible) 

Alternatively, we can have one report per input? So a report for {fasta, ont, ill}?

**Comment by MarieLataretu** [comment]
> Does this really work? multiple {fasta, ont, ill} in one run? Or do channels clash in such a scenario?

Yes, this works, since we have no else case here https://github.com/hoelzer/clean/blob/MarieLataretu/issue19/clean.nf#L356-L374.

> If it works, it's great but yes: how to do the reporting then. Intuitively, I would say that one run of the workflow will contain input data that is somehow related and thus a single report should be fine (if possible)

Yeah, I agree, you'd rather use files of a specific project and not just all reads from different projects.
So, I'll create one MultiQC report, that might get really big.

Do you think, it's added value to have quality reports of each 'step', so all reads, cleaned reads and contaminated reads?

**Comment by hoelzer** [comment]
Ok cool.

> Do you think, it's added value to have quality reports of each 'step', so all reads, cleaned reads and contaminated reads?

You mean FASTQC basically for all the steps? Hm, I think it can be interesting bc/ imagine that there is a certain contamination in a human sample by some bacteria. Now, in the FASTQC report you might see two peaks in the GC content. In the clean and contaminated FASTQC report you will only see one peak (hopefully). 

So I would say yes, it's interesting and should be not increase runtime that much. The only thing might be that - as you mentioned already - the report gets quite large.
