### ISSUE TITLE
minimap2 additional filter

### ISSUE THREAD

**Issue by hoelzer** [hoelzer/clean#23]
At the moment we just consider any read that minimaped a reference sequence to be contamination. 

However, this could result in filtering out small alignments. For example, only 50 nt align against DCS spike-in, but actually the read belongs to another closely related phage. 

We can think of a parameter that defines a certain alignment length (can we directly get this from the BAM?), for example we want at least 50% of the reference sequence length (e.g. DCS) covered to sort a read out as contaminant.

**Comment by MarieLataretu** [comment]
Kind of - we do not take the reference sequence into account, as described above, but that's fine with me for the moment!

**Comment by hoelzer** [comment]
Yep, same for me ;)
