### ISSUE TITLE
bbduk quality encoding change 

### ISSUE THREAD

**Issue by lisa-mariebarf** [hoelzer/clean#26]
Pls add a parameter so you can tell bbduk what ASCII quality encoding your input reads are. 
Default is ASCII-64, should be changeable to ASCII-33.

```  
Warning! Changed from ASCII-33 to ASCII-64 on input F: 70 -> 39
  Up to 396 prior reads may have been generated with incorrect qualities.
  If this is a problem you may wish to re-run with the flag 'qin=33' or 'qin=64'.

  The ASCII quality encoding offset (64) is not set correctly, or the reads are corrupt; quality value below -5.
  Please re-run with the flag 'qin=33', 'ignorebadquality', or '-da'.

```

**Comment by hoelzer** [comment]
Uhh, so some of your input reads are a bit older and have an older PHRED score encoding. Good to know that `bbduk` has issues with them.

**Comment by hoelzer** [comment]
Hm, the default is

```
qin=auto            Input quality offset: 33 (Sanger), 64, or auto.
```

so I guess the above one is really just a warning... nevertheless we can add a parameter and I will do so know. 

@MarieLataretu might make sense to use here the same procedure like we have in other workflows: something like `parma.sbbduk_additional_params` or so. So that the user can basically configure everything.

**Comment by hoelzer** [comment]
@lisa-mariebarf you can use now `--bbduk_qin` with the options {64, 33, auto}:

```
nextflow run clean.nf -profile local,docker --illumina 'test/illumina*.R{1,2}.fastq.gz'  --host eco --control phix --bbduk --bbduk_qin 33
```

The default is `auto`. 

Currently that is implemented in the branch `bbduk` and I will open a PR for @MarieLataretu to check and merge/release. 

@lisa-mariebarf If you want to use it now, clone the repo and switch to the branch

```
git checkout bbduk
nextflow run clean.nf ...
```

or wait for a release by @MarieLataretu  :)

**Comment by MarieLataretu** [comment]
Hi @lisa-mariebarf,
now it's fixed in the master branch :)
