### ISSUE TITLE
check for newlines when concat fastas

### ISSUE THREAD

**Issue by hoelzer** [hoelzer/clean#52]
```
Command error:
  [E::fai_build_core] Different line length in sequence 'NC_008066.1'
  [faidx] Could not build fai index db.fa.gz.fai
```

This happend to me while using phix and providing two mtDNA FASTAs from NCBI. For DCS it was working though. 

So I assume that the problem is that the integrated phiX FASTA has different line lengths as the two mtDNA FASTAs from NCBI

**Comment by hoelzer** [comment]
Hm, but actually the phix.fasta seems fine w/ the same line lengths... not sure

**Comment by hoelzer** [comment]
figured it:

```
>NC_053523.1 Gallus gallus isolate bGalGal1 mitochondrion, complete sequence, whole genome shotgun sequence
>NC_008066.1 Chlorocebus sabaeus mitochondrion, complete genome
CACGTTCCTCTTAAATAAGACATCTCGATG>gi|9626372|ref|NC_001422.1| Enterobacteria phage phiX174 sensu lato, complete genome
```

maybe it's good to add a newline to the FASTAs before cat!

**Comment by hoelzer** [comment]
DCS likely worked because it's not cated as the last file ;)

**Comment by MarieLataretu** [comment]
AAAha, now I get it. There was no newline at the end of the custom FASTA, right?

**Comment by MarieLataretu** [comment]
yeah, we check for `bgzip` compression anyway, that can happen also there!
