### ISSUE TITLE
samtools error caused by ncurses version information

### ISSUE THREAD

**Issue by imogen-foote** [hoelzer/clean#60]
Thanks for your efforts putting this tool together. I previously had the workflow running using the following command
`nextflow run hoelzer/clean --input_type nano --input /path/to/file.fastq.gz --host eco --control dcs --output /path/to/fastq/clean_output -profile singularity`

However I then tried to run it on the same fastq file adding in human as a host
`  nextflow run hoelzer/clean --input_type nano --input /path/to/file.fastq.gz --host eco,hsa --control dcs --output /path/to/fastq/clean_output -profile singularity
`
Ever since then I've had issues running the workflow regardless of whether I specify --host eco, --host eco,hsa or even just remove this line entirely (really all I want to do is remove the ONT DNA control sequence). I have also tried running on a different fastq file and get the same issue. The issues all seem to relate to samtools and the below message:

samtools: /opt/conda/bin/../lib/libtinfow.so.6: no version information available (required by samtools)
samtools: /opt/conda/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
samtools: /opt/conda/bin/../lib/libncursesw.so.6: no version information available (required by samtools)

Is this an issue with the container image, or more likely something with my system? 
Thanks heaps in advance!

**Comment by hoelzer** [comment]
Hey @imogen-foote thanks for using the pipeline!

Can you please try using a latest release version of CLEAN? E.g.

```bash
nextflow pull hoelzer/clean
nextflow run hoelzer/clean -r v1.0.0-beta ...
``` 

If this still fails, please let us know which process is failing. Yes, maybe there is a problem with the `samtools` version in the container. Also, if you can provide the `.nextflow.{log,err}` information from the working directory of the failed process that usually helps to solve the problem. 

thanks!

**Comment by hoelzer** [comment]
Hey, thanks! I think we identified the problem and need to switch to another container for minimap2: `nanozoo/minimap2:2.26--d9ef6b6`

We will let you know when there is a new version for testing.

**Comment by MarieLataretu** [comment]
HI @imogen-foote ,

I changed the minimap2 container (same version, but includes `ncurses`) - this should solve the problem!

The change is active in `-r master` or `-r v1.0.0-beta.1`. For `v1.0.0-beta.1`, please have a look at the [changelog](https://github.com/hoelzer/clean/blob/v1.0.0-beta.1/CHANGELOG.md#v100-beta---2023-09-30).

**Comment by imogen-foote** [comment]
Perfect, this is working for me now! Thank you
