### ISSUE TITLE
Add SARS-CoV-2 as a species

### ISSUE THREAD

**Issue by matthuska** [hoelzer/clean#62]
Would it make sense to add SARS-CoV-2 as a provided species? I'd be happy to do a PR if you think it would make sense, it should be pretty quick to implement.

I would use the reference as provided by ENA, if that is fine with you:

```
wget "https://www.ebi.ac.uk/ena/browser/api/fasta/MN908947.3?download=true" -O sc2.fasta
```

**Comment by hoelzer** [comment]
Ah yeah good idea! Yes, that should be easy to add and please feel free to sent an PR. The one from ENA is fine, it should be the same sequence like the one on NCBI just with a different ID.
