### ISSUE TITLE
Container for bedtools and samtools ("bed_samtools") is missing

### ISSUE THREAD

**Issue by matthuska** [hoelzer/clean#68]
There is a conda environment that contains bedtools and samtools, which is used by the `filter_true_dcs_alignments` process. No matching container exists though, causing a crash when the `-profile singularity --strict_dcs` options are used together.

**Comment by hoelzer** [comment]
Ah good find. 

Here you go:

nanozoo/bed_samtools:2.30.0--cc7d1b9

I used the same versions for samtools and bedtools as in https://github.com/hoelzer/clean/blob/master/envs/bed_samtools.yaml

And I did not build it in the rki-mf1 account bc all the other images we are using in CLEAN are also from the nanozoo organisation. To keep that consistant.
