### ISSUE TITLE
replace bowtie2 short-read clean w/ bbduk

### ISSUE THREAD

**Issue by hoelzer** [hoelzer/clean#9]
I found an easy way to decontaminate short-reads using bbduk. Code can be found and adjusted/copied from here:

https://github.com/hoelzer/mgnify-lr/blob/master/modules/bbduk.nf

**Comment by MarieLataretu** [comment]
I am wondering, how the bbduk.sh script is loaded in this module (https://github.com/hoelzer/mgnify-lr/blob/0c2db0bcdb2e7ba784f7651191bff6d8f9d1ecdb/modules/bbduk.nf#L48)

**Comment by hoelzer** [comment]
Ah, I think it's simply included in the docker image that is used: 

```java
withLabel: bbmap {      container = 'nanozoo/bbmap:38.79--07fb785' } 
```

I might have never tested this for a condo env...

**Comment by MarieLataretu** [comment]
okay, let's see if we can get this working without docker.

bbduk.sh calls some java stuff, that might be tricky

**Comment by MarieLataretu** [comment]
problem solved - there is a conda package :)

**Comment by hoelzer** [comment]
awesome :) ah yeah true, I also installed the tool in the docker via conda:

```bash
conda install bbmap=38.79
```

**Comment by MarieLataretu** [comment]
Just to be safe:

We have this output parameters for bbduk:
```
out=<file>          (outnonmatch) Write reads here that do not contain 
                    kmers matching the database.  'out=stdout.fq' will pipe 
                    to standard out.
out2=<file>         (outnonmatch2) Use this to write 2nd read of pairs to a 
                    different file.
outm=<file>         (outmatch) Write reads here that contain kmers matching
                    the database.
outm2=<file>        (outmatch2) Use this to write 2nd read of pairs to a 
                    different file.
```

I guess `database` is the `ref` parameter - in our case host_control.fa.

Now we want all matching reads to be clean, and not matching to be contaminated, so we need to set this, right?
```
out=${name}.contamination.R1.id.fastq out2=${name}.contamination.R2.id.fastq outm=${name}.clean.R1.id.fastq outm2=${name}.clean.R2.id.fastq
```

**Comment by MarieLataretu** [comment]
I see, it's the other way round!

We have a critical parameter with k:
```
k=27                Kmer length used for finding contaminants.  Contaminants 
                    shorter than k will not be found.  k must be at least 1.
```
I think, it should also be a (command line) parameter. And for default 27?

**Comment by hoelzer** [comment]
Exactly and Yeah, good idea to make this a Parameter and Set a default in
the nextflow.config!

MarieLataretu <notifications@github.com> schrieb am Fr., 10. Apr. 2020,
18:55:
